name: Intro GitHub Action

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # voir github marketplace github.com/actions/checkout

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run preview &
      - run: sleep 5
      - name: Curl the server to test if everything is ok
        run: curl -I http://localhost:4173
        
